### ISSUE TITLE
Rule suggestion: consistent usage of <React.Fragment> vs <>

### ISSUE THREAD

**Issue by rherms** [palantir/tslint-react#156]
Would be nice to have a rule for preferring <React.Fragment> over <>. Would love to try tackling this myself if I have the time.

**Comment by suchanlee** [comment]
I dont have much of an opinion here. One other advantage of <React.Fragment> vs <> is that <> cannot have attributes so for keyed fragments you need to use <React.Fragment> (https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#keyed-fragments)

Instead of preferring React.Fragment over <>, I think that it could be valuable to be enforce the usage of either one for consistency.

**Comment by jrparish** [comment]
I agree that it would be better for the rule to enforce consistency similar to this eslint rule - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

**Comment by adidahiya** [comment]
Closing due to deprecation timeline, see #210
