### ISSUE TITLE
Provide presets comparable to tslint:latest / tslint:recommended

### ISSUE THREAD

**Issue by digital-wonderland** [palantir/tslint-react#64]
Please correct me if I'm wrong, but currently one has to enable rules manually.

Would it instead please be possible to provide presets comparable to ```tslint:latest``` / ```tslint:recommended``` so one doesn't have to keep track of the current set of rules?

Reasoning would be the same as with TSLint - as in I don't want to argue / worry about code style but simply get the currently established best practice.

**Comment by adidahiya** [comment]
@digital-wonderland this is already available :)

as noted in the README -- just extend the config `"tslint-react"` -- TSLint "extends" functionality is built so that it will try to import a package of that name and try to import its "main" module (in the case of tslint-react, it's simply tslint-react.json in this repo) and interpret it as a config object.
